service: SFM-MissingStay

custom:
  serverless-aws-resource-names:
    source: serverless-mapping.json
  deploymentBucket:
    versioning: true
  DEV:
    deploymentBucket:
      name:  whg-s3-usw2a-codebase-dev
    cfnRole: "arn:aws:iam::520495760791:role/CloudformationRole"
    blueBucket: whg-s3-usw2a-blueterminal-dev
    errorBucket: whg-s3-usw2a-errorterminal-dev
    SNSTopicArn: "arn:aws:sns:us-west-2:520495760791:Missing-Stay-Excptn-Alerts-${opt:stage}"
    ENVIRONMENT: Non-Prod/UAT
    RECIPIENT: Rahul.Adepu@wyndham.com, Atik.Khatri@wyndham.com, shreyasi.nayek@wyndham.com
    SENDER: Chandrashekar.Kalva@wyndham.com
    awsAcctId: 520495760791
    tags:
      WHG-B-APPNM: SFM Missing Stay Email Reporting
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  QA:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-qa
    cfnRole: ''
    blueBucket: whg-s3-usw2a-blueterminal-qa
    errorBucket: whg-s3-usw2a-errorterminal-qa
    SNSTopicArn: "arn:aws:sns:us-west-2:520495760791:Missing-Stay-Excptn-Alerts-${opt:stage}"
    awsAcctId: 520495760791
    ENVIRONMENT: Non-Prod/UAT
    RECIPIENT: Atik.Khatri@wyndham.com, Lalit.Bajaj@wyndham.com, Siddhant.Mohril@wyndham.com, Surjeet.Das@wyndham.com, gary.vandover@wyndham.com, joel.maxwell@wyndham.com
    SENDER: Rahul.Adepu@wyndham.com
    tags:
      WHG-B-APPNM: SFM Missing Stay Email Reporting
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  PROD:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-prod
    cfnRole: ''
    blueBucket: whg-s3-usw2a-blueterminal-prod
    errorBucket: whg-s3-usw2a-errorterminal-prod
    SNSTopicArn: "arn:aws:sns:us-west-2:574950190833:Missing-Stay-Excptn-Alerts-${opt:stage}"
    awsAcctId: 574950190833
    ENVIRONMENT: Prod
    RECIPIENT: gary.vandover@wyndham.com, joel.maxwell@wyndham.com, TSSSupervisors@wyndham.com, Amanda.duchesne@wyndham.com, Kundai.mtunga@wyndham.com, RSD_NBR_HTCSOperationsAnalyst@wyndham.com, RSDNBRHTCSSystemsAnalyst@wyndham.com, RPASupport@wyndham.com
    SENDER: HIT_ProductionSystemsSupport@wyndham.com
    tags:
      WHG-B-APPNM: SFM Missing Stay Email Reporting
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP


provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: us-west-2
  cfnRole: ${self:custom.${opt:stage}.cfnRole}
  stackTags: ${self:custom.${opt:stage}.tags}
  deploymentBucket: 
    name: ${self:custom.${opt:stage}.deploymentBucket.name}
    serverSideEncryption: AES256
  deploymentPrefix: stay/scripts/lambda/missing-stay-email-notifs
  environment:
    blueBucket: ${self:custom.${opt:stage}.blueBucket}
    SNSTopicArn: ${self:custom.${opt:stage}.SNSTopicArn}
    errorBucket: ${self:custom.${opt:stage}.errorBucket}
    ENVIRONMENT: ${self:custom.${opt:stage}.ENVIRONMENT}
    RECIPIENT: ${self:custom.${opt:stage}.RECIPIENT}
    SENDER: ${self:custom.${opt:stage}.SENDER}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: 
        - "arn:aws:s3:::${self:custom.${opt:stage}.blueBucket}/*"
        - "arn:aws:s3:::${self:custom.${opt:stage}.errorBucket}/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: 
        - "arn:aws:s3:::${self:custom.${opt:stage}.blueBucket}"
        - "arn:aws:s3:::${self:custom.${opt:stage}.errorBucket}"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "${self:custom.${opt:stage}.SNSTopicArn}"
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: 
        - "*"
        
    
functions:
  EmailNotification:
    handler: handler.lambda_handler
    memorySize: 1024
    timeout: 300
    description: Lambda to send Missing Stay Email Notifications
    events:
      - s3:
          bucket: ${self:custom.${opt:stage}.blueBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: pms_stay/stay_transaction_table/missing_stay_report/
            - suffix: .xlsx
          existing: true

package:
  exclude:
    - serverless*.*
    - package*.*
    - node_modules/**

plugins:
  - serverless-aws-resource-names
  - serverless-deployment-bucket
  
  