# @Author : Rahul Adepu
# This yml script creates Lambda Function Layer which is a ZIP archive that has various dependant libraries and will be imported into different Lambda functions at runtime
# Note : 1.prior to execution of this yml, lambda scripts need to be zipped and uploaded to <scriptsPath>
#        2.layer should always have the latest code in its latest version so as to proceed with proper lambda function deployment (read 4.a step in repo/deploy-sit.ps1)
# Challenges faced: retaining the old version without deletion of old one-->solution- set UpdateReplacePolicy= Retain 

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a new layer for common code' 
Parameters:
  dataBucket:
    Type: String
    Default: irx-accumhub-dev-data
    Description: provides the bucket name where glue scripts, .whl and .zip needed for both Glue jobs and Lamda functions are resided.
  zipPath:
    Description: provides version number of zip file to be used for importing code to Lambda functions
    Type: String
    Default: deployment/irxah_common-0.1.zip
  layerName:
    Description: provides name of the layer to be used for importing code to Lambda functions
    Type: String
    Default: irxah-common-py
  descriptionForVersion:
    Description: description provide for each version
    Type: String
    Default: test layer used by ...
Resources:
  CommonLayer:
    Type: "AWS::Lambda::LayerVersion"
    #DeletionPolicy: Retain           
    UpdateReplacePolicy: Retain
    #this property will retain the older version(version-1) in the layer and appends new version (version-2) everytime you run the stack if and only if you change the value in parameter 'descriptionForVersion' or creates a new zip with canges in the code
    #if you just upload a different .zip with some code changes and you dont want to change the description, then it will override the previous version instead of creating a new
    Properties:
      LayerName: !Ref layerName
      Description: !Ref descriptionForVersion
      Content:
        S3Bucket: !Ref dataBucket
        S3Key: !Ref zipPath
      CompatibleRuntimes: 
        - python3.6
        - python3.7
        - python3.8
      # LicenseInfo: MIT
      # RetentionPolicy: Retain