AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stay Data Error Report Email Glue Formation Template'

####### Declaring parameters below

Parameters:
    JobName:
      Type: CommaDelimitedList
    IAMRoleName:
      Type: String
    IAMPolicyName:
      Type: String
    ScriptBucketName:
      Type: String
    LogBucketName:
      Type: String
    ErrorBucketName:
      Type: String
    RedshiftConnection:
      Type: String
    SNSTopic:
      Type: String
    Database:
      Type: String
    SchemaName:
      Type: String
    Environment:
      Type: String
    GlueTriggerName:
      Type: String
    
####### Adding Glue Job below
Resources:
    StayDataErrorEmail:
      Type: "AWS::Glue::Job"
      Properties:
        Role: !Ref GlueJobRole1
        Name: !Select [ 0, !Ref JobName ]
        GlueVersion: 2.0
        Command:
          Name: glueetl
          PythonVersion: 3
          ScriptLocation: !Sub s3://${ScriptBucketName}/stay_data_error_email/scripts/glue/stay_data_error_email_report.py
        DefaultArguments:
          "--extra-py-files": !Sub 's3://${ScriptBucketName}/stay_data_error_email/scripts/glue/libraries/openpyxl-3.0.9-py2.py3-none-any.whl,s3://${ScriptBucketName}/stay_data_error_email/scripts/glue/libraries/XlsxWriter-3.0.3-py3-none-any.whl'
          "--TempDir": !Sub 's3://${ScriptBucketName}/stay_data_error_email/scripts/glue/stay_data_error_email_report'
          "--enable-metrics": ''
          "--enable-continuous-cloudwatch-log": true
          "--enable-continuous-log-filter": true
          "--ScriptBucketName": !Ref ScriptBucketName
          "--schemaname": !Ref SchemaName
          "--blue_bucket": !Ref LogBucketName
          "--SNS": !Ref SnsTopic
          "--redshiftconnection": !Ref RedshiftConnection
          "--rsdb": !Ref Database
          "--env": !Ref Environment
        MaxRetries: 0
        MaxCapacity: 10
        Description: "stay data error email"
        Connections:
          Connections:
            - !Ref RedshiftConnection

####### Adding SNS Topic below
    SnsTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: !Ref SNSTopic
    SnsTopicSubscribe:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: !Ref SnsTopic
        Protocol: email
        Endpoint: WHRDataServices@wyndham.com
    SnsTopicSubscribeTwo:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: !Ref SnsTopic
        Protocol: email
        Endpoint: HIT_ProductionSystemsSupport@wyndham.com
        
    GlueTrigger:
      Type: AWS::Glue::Trigger
      Properties:
          Name: !Ref GlueTriggerName
          Type: SCHEDULED
          Description: "Stay Scheduled Trigger"
          Schedule: "cron(0 13 * * ? *)"
          StartOnCreation: true
          Actions:
              - JobName: !Ref StayDataErrorEmail

####### Adding Glue Job IAM Role below
    GlueJobRole1:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: !Ref IAMRoleName
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "glue.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: !Ref IAMPolicyName
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:GetObject"
                    - "s3:PutObject"
                  Resource:
                    - !Sub "arn:aws:s3:::${LogBucketName}/*"
                    - !Sub "arn:aws:s3:::${ErrorBucketName}/*"
                    - !Sub "arn:aws:s3:::${ScriptBucketName}/*"
                - Effect: "Allow"
                  Action:
                    - "s3:DeleteObject"
                  Resource:
                    - !Sub "arn:aws:s3:::${LogBucketName}/*"
                - Effect: "Allow"
                  Action:
                    - "s3:ListBucket"
                  Resource:
                    - !Sub "arn:aws:s3:::${LogBucketName}"
                    - !Sub "arn:aws:s3:::${ErrorBucketName}"
                    - !Sub "arn:aws:s3:::${ScriptBucketName}"
                - Effect: "Allow"
                  Action:
                    - "sns:Publish"
                  Resource:
                    - !Ref SnsTopic                
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"