INSERT INTO ahub_dw.custom_to_standard_mapping (mapping_id,client_file_id,row_type,src_col_position,dest_col_length,src_column_name,dest_col_position,conversion_type,dest_col_value,conversion_formula_id,description,created_by,created_timestamp,updated_by,updated_timestamp) 
VALUES
  (1,16,'Header',NULL,5,'Processing Routing Identification','1:5','REPLACE','20800',NULL,' Fills the value "20800" for the standard  header row for the position from 1 to 5 ',NULL,NULL,NULL,NULL),
  (2,16,'Header',NULL,14,'Processing Routing Identification','6:19','CUSTOM',NULL,'get_current_date_in_format("%m%d%Y%H%M%S","MST")',' Fills the current date in "MST" time zone with "MMDDYYYYHHmmss" format for the standard  header row for the position from 6 to 19 ',NULL,NULL,NULL,NULL),
  (3,16,'Header',NULL,181,'Processing Routing Identification','20:200','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " (space) for the standard  header row for the position from 20 to 200 ',NULL,NULL,NULL,NULL),
  (4,16,'Header',NULL,2,'Record Type','201:202','REPLACE','HD',NULL,' Fills the value "HD" for the standard  header row for the position from 201 to 202 ',NULL,NULL,NULL,NULL),
  (5,16,'Header',NULL,1,'Transmission Type','203:203','REPLACE','T',NULL,' Fills the value "T" for the standard  header row for the position in 203 ',NULL,NULL,NULL,NULL),
  (6,16,'Header','21:28',8,'Creation Date','204:211','CUSTOM',NULL,'convert_date_format(custom_value, "%Y%m%d", "%Y%m%d")',' Reads the data from custom file header line in the position from 21 to 28, which is in "CCYYMMDD" format and covert to format "YYYYMMDD", fills in the standard  header row for the position from 204 to 211 ',NULL,NULL,NULL,NULL),
  (7,16,'Header','29:32',4,'Creation Time','212:215','COPY_AS_IS',NULL,NULL,' Reads the data from custom file header line in the position from 29 to 32 and fills in the standard  header row for the position from 212 to 215 ',NULL,NULL,NULL,NULL),
  (8,16,'Header',NULL,30,'Sender ID','216:245','REPLACE','20800BCBSAZ',NULL,' Fills the value "20800BCBSAZ" for the standard  header row for the position from 216 to 245 with appended spaces at the right end ',NULL,NULL,NULL,NULL),
  (9,16,'Header',NULL,30,'Receiver ID','246:275','REPLACE','00489INGENIORX',NULL,' Fills the value "00489INGENIORX" for the standard  header row for the position from 246 to 275 with appended spaces at the right end ',NULL,NULL,NULL,NULL),
  (10,16,'Header',NULL,7,'Batch Number','276:282','REPLACE','0000001',NULL,' To be modified as the sequence number for every run ',NULL,NULL,NULL,NULL),
  (11,16,'Header','33:36',1,'File Type','283:283','CUSTOM',NULL,'_transform_values({"PROD": "P", "TEST": "T"}, custom_value," ")',' Reads the data from custom file header line in the position from 33 to 36, transforms the value to "P" if it is "PROD","T" id it is "TEST" and fills the transformed value in the standard  header row in the position 283 ',NULL,NULL,NULL,NULL),
  (12,16,'Header',NULL,2,'Version /Release Number','284:285','REPLACE','10',NULL,' Fills the value "10" for the standard  header row for the position from 284 to 285 ',NULL,NULL,NULL,NULL),
  (13,16,'Header',NULL,1415,'Reserved','286:1700','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " (space) for the standard  header row for the position from 286 to 1700 ',NULL,NULL,NULL,NULL),
  (14,16,'Footer',NULL,200,'Processor Routing Identification','1:200','CUSTOM',NULL,'header_row[0:200]',' Reads the value from the header_row (standard) in the position from 1 to 200 and fills in the standard  footer row for the position from 1 to 200 ',NULL,NULL,NULL,NULL),
  (15,16,'Footer',NULL,2,'Record Type','201:202','REPLACE','TR',NULL,' Fills the value "TR" for the standard  footer row for the position from 201 to 202 ',NULL,NULL,NULL,NULL),
  (16,16,'Footer',NULL,7,'Batch Number','203:209','CUSTOM',NULL,'header_row[275:282]',' Reads the value from the header_row (standard) in the position from 276 to 282 and fills in the standard  footer row for the position from 203 to 209 ',NULL,NULL,NULL,NULL),
  (17,16,'Footer','7:15',10,'Record Count','210:219','CUSTOM',NULL,'str(int(custom_value) - 2)',' Reads the data from custom file footer line in the position from 7 to 15, decrement the value by 2 and fills the result value in the standard  header row for the position from 210 to 219 ',NULL,NULL,NULL,NULL),
  (18,16,'Footer',NULL,80,'Message','220:299','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " (space) for the standard footer row for the position from 220 to 299 ',NULL,NULL,NULL,NULL),
  (19,16,'Footer',NULL,1401,'Reserved','300:1700','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " (space) for the standard  footer row for the position from 30 to 1700 ',NULL,NULL,NULL,NULL),
  (20,16,'Detail',NULL,200,'Processor Routing Identification','1:200','CUSTOM',NULL,'header_row[0:200]',' Reads the value from the header_row (standard) in the position from 1 to 200 and fills in the standard  detail row for the position from 1 to 200 ',NULL,NULL,NULL,NULL),
  (21,16,'Detail',NULL,2,'Record Type','201:202','REPLACE','DT',NULL,' Fills the value "DT" for the standard  detail row for the position from 201 to 202 ',NULL,NULL,NULL,NULL),
  (22,16,'Detail',NULL,2,'Transmission File Type','203:204','REPLACE','DQ',NULL,' Fills the value "DQ" for the standard  detail row for the position from 203 to 204 ',NULL,NULL,NULL,NULL),
  (23,16,'Detail',NULL,2,'Version/Release Number','205:206','REPLACE','10',NULL,' Fills the value "10" for the standard  detail row for the position from 205 to 206 ',NULL,NULL,NULL,NULL),
  (24,16,'Detail',NULL,30,'Sender ID','207:236','REPLACE','20800BCBSAZ',NULL,' Fills the value "20800BCBSAZ" for the standard  detail row for the position from 207 to 236 with appended spaces at the right end ',NULL,NULL,NULL,NULL),
  (25,16,'Detail',NULL,30,'Receiver ID','237:266','REPLACE','00489INGENIORX',NULL,' Fills the value "00489INGENIORX" for the standard  detail row for the position from 237 to 266 with appended spaces at the right end ',NULL,NULL,NULL,NULL),
  (26,16,'Detail',NULL,4,'Submission Number','267:270','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 267 to 270 ',NULL,NULL,NULL,NULL),
  (27,16,'Detail',NULL,1,'Transaction Response Status','271:271','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row in the position from 271 ',NULL,NULL,NULL,NULL),
  (28,16,'Detail',NULL,3,'Reject Code','272:274','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 272 to 274 ',NULL,NULL,NULL,NULL),
  (29,16,'Detail',NULL,5,'Record Length','275:279','REPLACE','01700',NULL,' Fills the value "01700" for the standard  detail row for the position from 275 to 279 ',NULL,NULL,NULL,NULL),
  (30,16,'Detail',NULL,20,'Reserved','280:299','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 280 to 299 ',NULL,NULL,NULL,NULL),
  (31,16,'Detail',NULL,8,'Transmission Date','300:307','CUSTOM',NULL,'header_row[203:211]',' Reads the value from the header_row (standard) in the position from 204 to 211 and fills in the standard  detail row for the position from 300 to 307 ',NULL,NULL,NULL,NULL),
  (32,16,'Detail',NULL,8,'Transmission Time','308:315','CUSTOM',NULL,'trim_and_combine_values((header_row[211:215], ''0000''))',' Reads the value from the header_row (standard) in the position from 212 to 215, then append "0000" value and fills in the standard  detail row for the position from 308 to 315 ',NULL,NULL,NULL,NULL),
  (33,16,'Detail','141:148',8,'Date of Service','316:323','CUSTOM',NULL,'get_later_date(custom_value, get_current_date_in_format("%Y%m%d","MST"), "%Y%m%d")',' Reads the data from custom file detail line in the position from 141 to 148, check with the current date and fills the higher date value in the standard  header row for the position from 316 to 323 ',NULL,NULL,NULL,NULL),
  (34,16,'Detail',NULL,2,'Service Provider ID Qualifier','324:325','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 324 to 325 ',NULL,NULL,NULL,NULL),
  (35,16,'Detail',NULL,15,'Service Provider ID','326:340','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 326 to 340 ',NULL,NULL,NULL,NULL),
  (36,16,'Detail',NULL,2,'Document Reference Identifier Qualifier','341:342','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 341 to 342 ',NULL,NULL,NULL,NULL),
  (37,16,'Detail',NULL,15,'Document Reference Identifier','343:357','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 343 to 357 ',NULL,NULL,NULL,NULL),
  (38,16,'Detail',NULL,14,'Transmission ID','358:371','CUSTOM',NULL,'get_current_date_in_format("%m%d%Y%H%M%S","MST")',' Fills the current date in "MST" time zone with "MMDDYYYYHHmmss" format for the standard  detail row for the position from 358 to 371 ',NULL,NULL,NULL,NULL),
  (39,16,'Detail',NULL,8,'Transmission ID','372:379','CUSTOM',NULL,'format_string(line_num, 8, ''0'', ''>'')',' Fills the line number prefixed with "0" with the length of 8 characters for the position from 372 to 379 ',NULL,NULL,NULL,NULL),
  (40,16,'Detail',NULL,28,'Transmission ID','380:407','CUSTOM',NULL,'format_string(''0'', 28, ''0'', ''>'')',' Fills the "0" with the length of 28 characters for the position from 380 to 407 ',NULL,NULL,NULL,NULL),
  (41,16,'Detail',NULL,1,'Benefit Type','408:408','REPLACE','9',NULL,' Fills the value "9" for the standard  detail row in the position in 408 ',NULL,NULL,NULL,NULL),
  (42,16,'Detail',NULL,1,'In Network Indicator','409:409','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position 409 ',NULL,NULL,NULL,NULL),
  (43,16,'Detail',NULL,1,'Formulary Status','410:410','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position 410 ',NULL,NULL,NULL,NULL),
  (44,16,'Detail',NULL,2,'Accumulator Action Code','411:412','REPLACE','00',NULL,' Fills the value "00" for the standard  detail row in the position from 411 to 412 ',NULL,NULL,NULL,NULL),
  (45,16,'Detail',NULL,30,'Sender Reference Number','413:442','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 413 to 442 ',NULL,NULL,NULL,NULL),
  (46,16,'Detail',NULL,20,'Insurance Code','443:462','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 443 to 462 ',NULL,NULL,NULL,NULL),
  (47,16,'Detail',NULL,1,'Accumulator Balance Benefit Type','463:463','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 463 to 463 ',NULL,NULL,NULL,NULL),
  (48,16,'Detail',NULL,8,'Benefit Effective Date','464:471','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 464 to 471 ',NULL,NULL,NULL,NULL),
  (49,16,'Detail',NULL,8,'Benefit Termination Date','472:479','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 472 to 479 ',NULL,NULL,NULL,NULL),
  (50,16,'Detail',NULL,1,'Accumulator Change Source Code','480:480','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 480 to 480 ',NULL,NULL,NULL,NULL),
  (51,16,'Detail',NULL,14,'Transaction ID','481:494','CUSTOM',NULL,'get_current_date_in_format("%m%d%Y%H%M%S","MST")',' Fills the current date in "MST" time zone with "MMDDYYYYHHmmss" format for the standard  detail row for the position from 481 to 494 ',NULL,NULL,NULL,NULL),
  (52,16,'Detail',NULL,8,'Transaction ID','495:502','CUSTOM',NULL,'format_string(line_num, 8, ''0'',  ''>'')',' Fills the line number prefixed with "0" with the length of 8 characters for the position from 495 to 502 ',NULL,NULL,NULL,NULL),
  (53,16,'Detail','',8,'Transaction ID','503:510','CUSTOM',NULL,'format_string(''0'', 8, ''0'', ''>'')',' Fills the "0" with the length of 8 characters for the position from 503 to 510 ',NULL,NULL,NULL,NULL),
  (54,16,'Detail',NULL,30,'Transaction ID Cross Reference','511:540','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 511 to 540 ',NULL,NULL,NULL,NULL),
  (55,16,'Detail',NULL,1,'Adjustment Reason Code','541:541','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 541 to 541 ',NULL,NULL,NULL,NULL),
  (56,16,'Detail',NULL,26,'Accumulator Reference Time Stamp','542:567','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 542 to 567 ',NULL,NULL,NULL,NULL),
  (57,16,'Detail',NULL,13,'Reserved','568:580','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 568 to 580 ',NULL,NULL,NULL,NULL),
  (58,16,'Detail','14:38',20,'Cardholder ID','581:600','COPY_AS_IS',NULL,NULL,' Reads the data from custom file detail line in the position from 14 to 38,  and fills in standard  detail row for the position from 581 to 600. ',NULL,NULL,NULL,NULL),
  (59,16,'Detail',NULL,15,'Group ID','601:615','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 601 to 615 ',NULL,NULL,NULL,NULL),
  (60,16,'Detail','85:109',25,'Patient First Name','616:640','COPY_AS_IS',NULL,NULL,' Reads the data from custom file detail line in the position from 85 to 109, and fills in standard  detail row for the position from 616 to 640. ',NULL,NULL,NULL,NULL),
  (61,16,'Detail','110:110',1,'Middle Initial','641:641','COPY_AS_IS',NULL,NULL,' Reads the data from custom file detail line in the position from 110, and fills in standard  detail row for in position 641. ',NULL,NULL,NULL,NULL),
  (62,16,'Detail','50:84',35,'Patient Last Name','642:676','COPY_AS_IS',NULL,NULL,' Reads the data from custom file detail line in the position from 50 to 84, and fills in standard  detail row for the position from 642 to 676. ',NULL,NULL,NULL,NULL),
  (63,16,'Detail',NULL,1,'Patient Relationship Code','677:677','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 677 ',NULL,NULL,NULL,NULL),
  (64,16,'Detail','42:49',8,'Date of Birth','678:685','COPY_AS_IS',NULL,NULL,' Reads the data from custom file detail line in the position from 42 to 49, and fills in standard  detail row for the position from 678 to 685. ',NULL,NULL,NULL,NULL),
  (65,16,'Detail','41:41',1,'Patient Gender Code','686:686','CUSTOM',NULL,'_transform_values({"M": "1", "F": "2"},custom_value, " ")',' Reads the data from custom file detail line in the position 41, transforms the value to "1" if it is "M","2" if it is "F" and fills the transformed value in the standard  detail row in the position 686 ',NULL,NULL,NULL,NULL),
  (66,16,'Detail',NULL,2,'Patient State/Province Address','687:688','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 687 to 688 ',NULL,NULL,NULL,NULL),
  (67,16,'Detail',NULL,35,'Cardholder Last Name','689:723','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 689 to 723 ',NULL,NULL,NULL,NULL),
  (68,16,'Detail',NULL,9,'Carrier Number','724:732','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 724 to 732 ',NULL,NULL,NULL,NULL),
  (69,16,'Detail',NULL,15,'Contract Number','733:747','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 733 to 747 ',NULL,NULL,NULL,NULL),
  (70,16,'Detail',NULL,50,'Client Pass Through','748:797','REPLACE','INGENIORXGILA00489',NULL,' Fills the value "INGENIORXGILA00489" for the standard  detail row for the position from 748 to 797 with appended spaces at the right end ',NULL,NULL,NULL,NULL),
  (71,16,'Detail',NULL,20,'Family ID Number','798:817','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 798 to 817 ',NULL,NULL,NULL,NULL),
  (72,16,'Detail',NULL,20,'Cardholder ID (Alternate)','818:837','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 818 to 837 ',NULL,NULL,NULL,NULL),
  (73,16,'Detail',NULL,15,'Group ID (Alternate)','838:852','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 838 to 852 ',NULL,NULL,NULL,NULL),
  (74,16,'Detail',NULL,20,'Patient ID','853:872','CUSTOM',NULL,'trim_and_combine_values([custom_row[13:38],custom_row[38:40]])',' Read and combines the value from the custom_row in the position from 13 to 38, and  in the position from 38 to 40and fills in the standard  detail row for the position from 853 to 872 ',NULL,NULL,NULL,NULL),
  (75,16,'Detail',NULL,3,'Person Code','873:875','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 873 to 875 ',NULL,NULL,NULL,NULL),
  (76,16,'Detail',NULL,90,'Reserved','876:965','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 876 to 965 ',NULL,NULL,NULL,NULL),
  (77,16,'Detail',NULL,2,'Accumulator Balance Count','966:967','REPLACE','01',NULL,' Fills the value "01" for the standard  detail row for the position from 966 to 967 ',NULL,NULL,NULL,NULL),
  (78,16,'Detail',NULL,2,'Accumulator Specific Category Type','968:969','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 968 to 969 ',NULL,NULL,NULL,NULL),
  (79,16,'Detail',NULL,20,'Reserved','970:989','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 970 to 989 ',NULL,NULL,NULL,NULL),
  (80,16,'Detail','111:120',2,'Accumulator Balance Qualifier','990:991','CUSTOM',NULL,'_transform_values({"OOPHGRIIND": "05", "OOPHGROIND": "05"},custom_value, "99")',' Reads the data from custom file detail line in the position from 111 to 120, transforms the value to "05" if it is "OOPHGRIIND" or "OOPHGRIIND","99" if it is anything else and fills the transformed value in the standard  detail row in the position from 990 to 991 ',NULL,NULL,NULL,NULL),
  (81,16,'Detail','111:120',1,'Accumulator Network Indicator','992:992','CUSTOM',NULL,'_transform_values({"OOPHGRIIND": "1", "OOPHGROIND": "2"},custom_value, "0")',' Reads the data from custom file detail line in the position from 111 to 120, transforms the value to "1" if it is "OOPHGRIIND" ,"2" if it is "OOPHGRIIND","0" if it is anything else and fills the transformed value in the standard  detail row in the position in 992 ',NULL,NULL,NULL,NULL),
  (82,16,'Detail','122:132',10,'Accumulator Applied Amount','993:1002','CUSTOM',NULL,'format_string(_get_lower_amount(custom_value, 99999999, 999999999), 10, "0", ">")',' Reads the value from custom detail line in the position from 122 to 132 (skipping the sign) and compare with the value 99999999. If it is greater than 99999999 then fill with amount 999999999. Else fill with actual amount from custom line), then format the number prefixed with zero to make 10 char length ',NULL,NULL,NULL,NULL),
  (83,16,'Detail',NULL,1,'Action Code','1003:1003','REPLACE','R',NULL,' Fills the value "R" for the standard  detail row for the position in 1003 ',NULL,NULL,NULL,NULL),
  (84,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1004:1013','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1004 to 1013 ',NULL,NULL,NULL,NULL),
  (85,16,'Detail',NULL,1,'Action Code','1014:1014','REPLACE','+',NULL,' Fills the value "+" for the standard  detail row for the position in 1014 ',NULL,NULL,NULL,NULL),
  (86,16,'Detail',NULL,10,'Accumulator Remaining Balance','1015:1024','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1015 to 1024 ',NULL,NULL,NULL,NULL),
  (87,16,'Detail',NULL,1,'Action Code','1025:1025','REPLACE','+',NULL,' Fills the value "+" for the standard  detail row for the position in 1025 ',NULL,NULL,NULL,NULL),
  (88,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1026:1027','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 1026 to 1027 ',NULL,NULL,NULL,NULL),
  (89,16,'Detail',NULL,1,'Accumulator Network Indicator','1028:1028','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1028 ',NULL,NULL,NULL,NULL),
  (90,16,'Detail',NULL,10,'Accumulator Applied Amount','1029:1038','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1029 to 1038 ',NULL,NULL,NULL,NULL),
  (91,16,'Detail',NULL,1,'Action Code','1039:1039','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1039 ',NULL,NULL,NULL,NULL),
  (92,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1040:1049','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1040 to 1049 ',NULL,NULL,NULL,NULL),
  (93,16,'Detail',NULL,1,'Action Code','1050:1050','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1050 ',NULL,NULL,NULL,NULL),
  (94,16,'Detail',NULL,10,'Accumulator Remaining Balance','1051:1060','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1051 to 1060 ',NULL,NULL,NULL,NULL),
  (95,16,'Detail',NULL,1,'Action Code','1061:1061','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1061 ',NULL,NULL,NULL,NULL),
  (96,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1062:1063','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position from 1062 to 1063 ',NULL,NULL,NULL,NULL),
  (97,16,'Detail',NULL,1,'Accumulator Network Indicator','1064:1064','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1064 ',NULL,NULL,NULL,NULL),
  (98,16,'Detail',NULL,10,'Accumulator Applied Amount','1065:1074','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1065 to 1074 ',NULL,NULL,NULL,NULL),
  (99,16,'Detail',NULL,1,'Action Code','1075:1075','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1075 ',NULL,NULL,NULL,NULL),
  (100,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1076:1085','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1076 to 1085 ',NULL,NULL,NULL,NULL),
  (101,16,'Detail',NULL,1,'Action Code','1086:1086','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1086 ',NULL,NULL,NULL,NULL),
  (102,16,'Detail',NULL,10,'Accumulator Remaining Balance','1087:1096','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position from 1087 to 1096 ',NULL,NULL,NULL,NULL),
  (103,16,'Detail',NULL,1,'Action Code','1097:1097','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position in 1097 ',NULL,NULL,NULL,NULL),
  (104,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1098:1099','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1098 to 1099 ',NULL,NULL,NULL,NULL),
  (105,16,'Detail',NULL,1,'Accumulator Network Indicator','1100:1100','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1100 ',NULL,NULL,NULL,NULL),
  (106,16,'Detail',NULL,10,'Accumulator Applied Amount','1101:1110','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1101 to 1110 ',NULL,NULL,NULL,NULL),
  (107,16,'Detail',NULL,1,'Action Code','1111:1111','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1111 ',NULL,NULL,NULL,NULL),
  (108,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1112:1121','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1112 to 1121 ',NULL,NULL,NULL,NULL),
  (109,16,'Detail',NULL,1,'Action Code','1122:1122','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1122 ',NULL,NULL,NULL,NULL),
  (110,16,'Detail',NULL,10,'Accumulator Remaining Balance','1123:1132','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1123 to 1132 ',NULL,NULL,NULL,NULL),
  (111,16,'Detail',NULL,1,'Action Code','1133:1133','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1133 ',NULL,NULL,NULL,NULL),
  (112,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1134:1135','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1134 to 1135 ',NULL,NULL,NULL,NULL),
  (113,16,'Detail',NULL,1,'Accumulator Network Indicator','1136:1136','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1136 ',NULL,NULL,NULL,NULL),
  (114,16,'Detail',NULL,10,'Accumulator Applied Amount','1137:1146','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1137 to 1146 ',NULL,NULL,NULL,NULL),
  (115,16,'Detail',NULL,1,'Action Code','1147:1147','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1147 ',NULL,NULL,NULL,NULL),
  (116,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1148:1157','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1148 to 1157 ',NULL,NULL,NULL,NULL),
  (117,16,'Detail',NULL,1,'Action Code','1158:1158','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1158 ',NULL,NULL,NULL,NULL),
  (118,16,'Detail',NULL,10,'Accumulator Remaining Balance','1159:1168','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1159 to 1168 ',NULL,NULL,NULL,NULL),
  (119,16,'Detail',NULL,1,'Action Code','1169:1169','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1169 ',NULL,NULL,NULL,NULL),
  (120,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1170:1171','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1170 to 1171 ',NULL,NULL,NULL,NULL),
  (121,16,'Detail',NULL,1,'Accumulator Network Indicator','1172:1172','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1172 ',NULL,NULL,NULL,NULL),
  (122,16,'Detail',NULL,10,'Accumulator Applied Amount','1173:1182','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1173 to 1182 ',NULL,NULL,NULL,NULL),
  (123,16,'Detail',NULL,1,'Action Code','1183:1183','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1183 ',NULL,NULL,NULL,NULL),
  (124,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1184:1193','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1184 to 1193 ',NULL,NULL,NULL,NULL),
  (125,16,'Detail',NULL,1,'Action Code','1194:1194','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1194 ',NULL,NULL,NULL,NULL),
  (126,16,'Detail',NULL,10,'Accumulator Remaining Balance','1195:1204','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1195 to 1204 ',NULL,NULL,NULL,NULL),
  (127,16,'Detail',NULL,1,'Action Code','1205:1205','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1205 ',NULL,NULL,NULL,NULL),
  (128,16,'Detail',NULL,24,'Reserved','1206:1229','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1206 to 1229 ',NULL,NULL,NULL,NULL),
  (129,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1230:1231','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1230 to 1231 ',NULL,NULL,NULL,NULL),
  (130,16,'Detail',NULL,1,'Accumulator Network Indicator','1232:1232','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1232 ',NULL,NULL,NULL,NULL),
  (131,16,'Detail',NULL,10,'Accumulator Applied Amount','1233:1242','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1233 to 1242 ',NULL,NULL,NULL,NULL),
  (132,16,'Detail',NULL,1,'Action Code','1243:1243','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1243 ',NULL,NULL,NULL,NULL),
  (133,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1244:1253','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1244 to 1253 ',NULL,NULL,NULL,NULL),
  (134,16,'Detail',NULL,1,'Action Code','1254:1254','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1254 ',NULL,NULL,NULL,NULL),
  (135,16,'Detail',NULL,10,'Accumulator Remaining Balance','1255:1264','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1255 to 1264 ',NULL,NULL,NULL,NULL),
  (136,16,'Detail',NULL,1,'Action Code','1265:1265','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1265 ',NULL,NULL,NULL,NULL),
  (137,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1266:1267','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1266 to 1267 ',NULL,NULL,NULL,NULL),
  (138,16,'Detail',NULL,1,'Accumulator Network Indicator','1268:1268','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1268 to 1268 ',NULL,NULL,NULL,NULL),
  (139,16,'Detail',NULL,10,'Accumulator Applied Amount','1269:1278','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1269 to 1278 ',NULL,NULL,NULL,NULL),
  (140,16,'Detail',NULL,1,'Action Code','1279:1279','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1279 to 1279 ',NULL,NULL,NULL,NULL),
  (141,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1280:1289','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1280 to 1289 ',NULL,NULL,NULL,NULL),
  (142,16,'Detail',NULL,1,'Action Code','1290:1290','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1290 to 1290 ',NULL,NULL,NULL,NULL),
  (143,16,'Detail',NULL,10,'Accumulator Remaining Balance','1291:1300','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1291 to 1300 ',NULL,NULL,NULL,NULL),
  (144,16,'Detail',NULL,1,'Action Code','1301:1301','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1301 to 1301 ',NULL,NULL,NULL,NULL),
  (145,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1302:1303','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1302 to 1303 ',NULL,NULL,NULL,NULL),
  (146,16,'Detail',NULL,1,'Accumulator Network Indicator','1304:1304','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1304 ',NULL,NULL,NULL,NULL),
  (147,16,'Detail',NULL,10,'Accumulator Applied Amount','1305:1314','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1305 to 1314 ',NULL,NULL,NULL,NULL),
  (148,16,'Detail',NULL,1,'Action Code','1315:1315','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1315 ',NULL,NULL,NULL,NULL),
  (149,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1316:1325','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1316 to 1325 ',NULL,NULL,NULL,NULL),
  (150,16,'Detail',NULL,1,'Action Code','1326:1326','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1326 ',NULL,NULL,NULL,NULL),
  (151,16,'Detail',NULL,10,'Accumulator Remaining Balance','1327:1336','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1327 to 1336 ',NULL,NULL,NULL,NULL),
  (152,16,'Detail',NULL,1,'Action Code','1337:1337','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1337 ',NULL,NULL,NULL,NULL),
  (153,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1338:1339','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1338 to 1339 ',NULL,NULL,NULL,NULL),
  (154,16,'Detail',NULL,1,'Accumulator Network Indicator','1340:1340','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1340 ',NULL,NULL,NULL,NULL),
  (155,16,'Detail',NULL,10,'Accumulator Applied Amount','1341:1350','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1341 to 1350 ',NULL,NULL,NULL,NULL),
  (156,16,'Detail',NULL,1,'Action Code','1351:1351','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1351 ',NULL,NULL,NULL,NULL),
  (157,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1352:1361','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1352 to 1361 ',NULL,NULL,NULL,NULL),
  (158,16,'Detail',NULL,1,'Action Code','1362:1362','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1362 ',NULL,NULL,NULL,NULL),
  (159,16,'Detail',NULL,10,'Accumulator Remaining Balance','1363:1372','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1363 to 1372 ',NULL,NULL,NULL,NULL),
  (160,16,'Detail',NULL,1,'Action Code','1373:1373','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1373 ',NULL,NULL,NULL,NULL),
  (161,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1374:1375','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1374 to 1375 ',NULL,NULL,NULL,NULL),
  (162,16,'Detail',NULL,1,'Accumulator Network Indicator','1376:1376','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1376 ',NULL,NULL,NULL,NULL),
  (163,16,'Detail',NULL,10,'Accumulator Applied Amount','1377:1386','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1377 to 1386 ',NULL,NULL,NULL,NULL),
  (164,16,'Detail',NULL,1,'Action Code','1387:1387','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1387 ',NULL,NULL,NULL,NULL),
  (165,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1388:1397','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1388 to 1397 ',NULL,NULL,NULL,NULL),
  (166,16,'Detail',NULL,1,'Action Code','1398:1398','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1398 ',NULL,NULL,NULL,NULL),
  (167,16,'Detail',NULL,10,'Accumulator Remaining Balance','1399:1408','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1399 to 1408 ',NULL,NULL,NULL,NULL),
  (168,16,'Detail',NULL,1,'Action Code','1409:1409','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1409 ',NULL,NULL,NULL,NULL),
  (169,16,'Detail',NULL,2,'Accumulator Balance Qualifier','1410:1411','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1410 to 1411 ',NULL,NULL,NULL,NULL),
  (170,16,'Detail',NULL,1,'Accumulator Network Indicator','1412:1412','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1412 ',NULL,NULL,NULL,NULL),
  (171,16,'Detail',NULL,10,'Accumulator Applied Amount','1413:1422','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1413 to 1422 ',NULL,NULL,NULL,NULL),
  (172,16,'Detail',NULL,1,'Action Code','1423:1423','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1423 ',NULL,NULL,NULL,NULL),
  (173,16,'Detail',NULL,10,'Accumulator Benefit Period Amount','1424:1433','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1424 to 1433 ',NULL,NULL,NULL,NULL),
  (174,16,'Detail',NULL,1,'Action Code','1434:1434','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1434 ',NULL,NULL,NULL,NULL),
  (175,16,'Detail',NULL,10,'Accumulator Remaining Balance','1435:1444','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1435 to 1444 ',NULL,NULL,NULL,NULL),
  (176,16,'Detail',NULL,1,'Action Code','1445:1445','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1445 ',NULL,NULL,NULL,NULL),
  (177,16,'Detail',NULL,1,'Optional Data Indicator','1446:1446','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1446 ',NULL,NULL,NULL,NULL),
  (178,16,'Detail',NULL,10,'Total Amount Paid','1447:1456','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1447 to 1456 ',NULL,NULL,NULL,NULL),
  (179,16,'Detail',NULL,1,'Action Code','1457:1457','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1457 ',NULL,NULL,NULL,NULL),
  (180,16,'Detail',NULL,10,'Amount of Copay','1458:1467','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1458 to 1467 ',NULL,NULL,NULL,NULL),
  (181,16,'Detail',NULL,1,'Action Code','1468:1468','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1468 ',NULL,NULL,NULL,NULL),
  (182,16,'Detail',NULL,10,'Patient Pay Amount','1469:1478','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1469 to 1478 ',NULL,NULL,NULL,NULL),
  (183,16,'Detail',NULL,1,'Action Code','1479:1479','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1479 ',NULL,NULL,NULL,NULL),
  (184,16,'Detail',NULL,10,'Amount Attributed to Product Selection/Brand','1480:1489','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1480 to 1489 ',NULL,NULL,NULL,NULL),
  (185,16,'Detail',NULL,1,'Action Code','1490:1490','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1490 ',NULL,NULL,NULL,NULL),
  (186,16,'Detail',NULL,10,'Amount Attributed to Sales Tax','1491:1500','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1491 to 1500 ',NULL,NULL,NULL,NULL),
  (187,16,'Detail',NULL,1,'Action Code','1501:1501','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1501 ',NULL,NULL,NULL,NULL),
  (188,16,'Detail',NULL,10,'Amount Attributed to Processor Fee','1502:1511','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1502 to 1511 ',NULL,NULL,NULL,NULL),
  (189,16,'Detail',NULL,1,'Action Code','1512:1512','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1512 ',NULL,NULL,NULL,NULL),
  (190,16,'Detail',NULL,10,'Gross Amount Due','1513:1522','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1513 to 1522 ',NULL,NULL,NULL,NULL),
  (191,16,'Detail',NULL,1,'Action Code','1523:1523','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1523 ',NULL,NULL,NULL,NULL),
  (192,16,'Detail',NULL,10,'Invoiced Amount','1524:1533','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1524 to 1533 ',NULL,NULL,NULL,NULL),
  (193,16,'Detail',NULL,1,'Action Code','1534:1534','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1534 ',NULL,NULL,NULL,NULL),
  (194,16,'Detail',NULL,10,'Penalty Amount','1535:1544','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1535 to 1544 ',NULL,NULL,NULL,NULL),
  (195,16,'Detail',NULL,1,'Action Code','1545:1545','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1545 ',NULL,NULL,NULL,NULL),
  (196,16,'Detail',NULL,23,'Reserved','1546:1568','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1546 to 1568 ',NULL,NULL,NULL,NULL),
  (197,16,'Detail',NULL,2,'Product/Service ID Qualifier','1569:1570','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1569 to 1570 ',NULL,NULL,NULL,NULL),
  (198,16,'Detail',NULL,19,'0','1571:1589','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1571 to 1589 ',NULL,NULL,NULL,NULL),
  (199,16,'Detail',NULL,3,'Days Supply','1590:1592','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1590 to 1592 ',NULL,NULL,NULL,NULL),
  (200,16,'Detail',NULL,10,'Quantity Dispensed','1593:1602','FILL_WITH_THIS_VALUE','0',NULL,' Fills "0" for the standard  detail row for the position  from 1593 to 1602 ',NULL,NULL,NULL,NULL),
  (201,16,'Detail',NULL,30,'Product/Service Name','1603:1632','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1603 to 1632 ',NULL,NULL,NULL,NULL),
  (202,16,'Detail',NULL,1,'Brand/Generic Indicator','1633:1633','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1633 ',NULL,NULL,NULL,NULL),
  (203,16,'Detail',NULL,1,'Therapeutic Class Code Qualifier','1634:1634','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1634 ',NULL,NULL,NULL,NULL),
  (204,16,'Detail',NULL,17,'Therapeutic Class Code','1635:1651','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1635 to 1651 ',NULL,NULL,NULL,NULL),
  (205,16,'Detail',NULL,1,'Dispensed As Written (DAW)/Product Selection','1652:1652','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  in 1652 ',NULL,NULL,NULL,NULL),
  (206,16,'Detail',NULL,48,'Reserved','1653:1700','FILL_WITH_THIS_VALUE',' ',NULL,' Fills " " for the standard  detail row for the position  from 1653 to 1700 ',NULL,NULL,NULL,NULL);

UPDATE ahub_dw.custom_to_standard_mapping
   SET conversion_formula_id = 'format_string(str(int(custom_value) - 2), 10, ''0'', ''>'')'
WHERE mapping_id = 17;

UPDATE ahub_dw.custom_to_standard_mapping
   SET conversion_type = 'CUSTOM',
       conversion_formula_id = 'format_string(str(batch_number), 7, ''0'', ''>'')',
       dest_col_value = NULL
WHERE mapping_id = 10;

UPDATE ahub_dw.client_files
   SET file_timezone = 'America/Phoenix'
WHERE client_file_id = 16;

UPDATE ahub_dw.client_files
   SET validate_file_structure = TRUE
WHERE client_file_id = 16;

UPDATE ahub_dw.custom_to_standard_mapping
   SET conversion_formula_id = 'get_earlier_date(custom_value, get_current_date_in_format("%Y%m%d","MST"), "%Y%m%d")',
       description = 'Reads the data from custom file detail line in the position from 141 to 148, check with the current date and fills the minimum date value in the standard  header row for the position from 316 to 323 .
#1 if Counter Accum End Date(141:148) >= Run Date(current date) then Date of Service = Run date
#2 if Counter Accum End Date(141:148) < Run Date(current date) then Date of Service = Counter Accum End Date'
WHERE mapping_id = 33;

UPDATE ahub_dw.custom_to_standard_mapping
   SET dest_col_value = '0',
       description = ' Fills "0" for the standard  detail row for the position from 464 to 471 '
WHERE mapping_id = 48;

UPDATE ahub_dw.custom_to_standard_mapping
   SET dest_col_value = '0',
       description = ' Fills "0" for the standard  detail row for the position from 733 to 747 '
WHERE mapping_id = 69;

UPDATE ahub_dw.custom_to_standard_mapping
   SET conversion_formula_id = 'format_string(_get_lower_amount(custom_value, 9999999999, 9999999999), 10, "0", ">")',
       description = 'Reads the value from custom detail line in the position from 122 to 132 (skipping the sign) and compare with the value 9999999999. If it is greater than 9999999999 then fill with amount 9999999999. Else fill with actual amount from custom line), then format the number prefixed with zero to make 10 char length '
WHERE mapping_id = 82;

UPDATE ahub_dw.custom_to_standard_mapping
   SET src_col_position = null,
       conversion_type = 'FILL_WITH_THIS_VALUE',
       dest_col_value = ' ',
       description = 'Fills " " for the standard  detail row for the position from 581 to 600'
WHERE mapping_id = 58;

UPDATE ahub_dw.custom_to_standard_mapping
   SET src_col_position = '14:38',
       conversion_formula_id = '_get_patient_id(custom_value,20,"9")',
       description = 'Read the value from the custom_row in the position from 14 to 38, trim the custom value and if length of custom value is greater than 20 then fill with all 9s, else the trimmed value in standard detail row for the position from 853 to 872'
WHERE mapping_id = 74;

COMMIT;


