CREATE OR REPLACE VIEW AHUB_DW.VW_ACCUMULATOR_DETAIL_DETOKENIZED AS (
SELECT 
ACCUMULATOR_DETAIL_KEY                                  
,PROCESSOR_ROUTING_IDENTIFICATION                        
,RECORD_TYPE                                             
,TRANSMISSION_FILE_TYPE                                  
,VERSION_RELEASE_NUMBER                                  
,SENDER_IDENTIFIER                                       
,RECEIVER_IDENTIFIER                                     
,SUBMISSION_NUMBER                                       
,TRANSACTION_RESPONSE_STATUS                             
,REJECT_CODE                                             
,RECORD_LENGTH                                           
,RESERVED_1                                              
,TRANSMISSION_DATE                                       
,TRANSMISSION_TIME                                       
,DATE_OF_SERVICE                                           
,SERVICE_PROVIDER_IDENTIFIER_QUALIFIER                   
,SERVICE_PROVIDER_IDENTIFIER                             
,DOCUMENT_REFERENCE_IDENTIFIER_QUALIFIER                 
,DOCUMENT_REFERENCE_IDENTIFIER                           
,TRANSMISSION_IDENTIFIER                                 
,BENEFIT_TYPE                                            
,IN_NETWORK_INDICATOR                                    
,FORMULARY_STATUS                                        
,ACCUMULATOR_ACTION_CODE                                 
,SENDER_REFERENCE_NUMBER                                 
,INSURANCE_CODE                                          
,ACCUMULATOR_BALANCE_BENEFIT_TYPE                        
,BENEFIT_EFFECTIVE_DATE                                  
,BENEFIT_TERMINATION_DATE                                
,ACCUMULATOR_CHANGE_SOURCE_CODE                          
,TRANSACTION_IDENTIFIER                                  
,TRANSACTION_IDENTIFIER_CROSS_REFERENCE                  
,ADJUSTMENT_REASON_CODE                                  
,ACCUMULATOR_REFERENCE_TIME_STAMP                        
,RESERVED_2      
,CARDHOLDER_IDENTIFIER                                        
,concat(concat('~I', CARDHOLDER_IDENTIFIER), 'I`~')  CARDHOLDER_IDENTIFIER_PHI                                   
,GROUP_IDENTIFIER              
,PATIENT_FIRST_NAME                          
,concat(concat('~N', PATIENT_FIRST_NAME), 'N`~') PATIENT_FIRST_NAME_PHI
,MIDDLE_INITIAL                                     
,concat(concat('~N', MIDDLE_INITIAL), 'N`~')  MIDDLE_INITIAL_PHI
,PATIENT_LAST_NAME                                          
,concat(concat('~N', PATIENT_LAST_NAME), 'N`~') PATIENT_LAST_NAME_PHI                                       
,PATIENT_RELATIONSHIP_CODE        
,DATE_OF_BIRTH                       
,concat(concat('~D', DATE_OF_BIRTH), 'D`~') DATE_OF_BIRTH_PHI                                           
,PATIENT_GENDER_CODE                                     
,PATIENT_STATE_PROVINCE_ADDRESS 
,CARDHOLDER_LAST_NAME                         
,concat(concat('~N', CARDHOLDER_LAST_NAME), 'N`~') CARDHOLDER_LAST_NAME_PHI                                    
,CARRIER_NUMBER                                          
,CONTRACT_NUMBER                                         
,CLIENT_PASS_THROUGH               
,FAMILY_IDENTIFIER_NUMBER                      
,concat(concat('~I', FAMILY_IDENTIFIER_NUMBER), 'I`~')  FAMILY_IDENTIFIER_NUMBER_PHI
,CARDHOLDER_IDENTIFIER_ALTERNATE                                
,concat(concat('~I', CARDHOLDER_IDENTIFIER_ALTERNATE), 'I`~')  CARDHOLDER_IDENTIFIER_ALTERNATE_PHI                         
,GROUP_IDENTIFIER_ALTERNATE 
,PATIENT_IDENTIFIER                             
,concat(concat('~I', PATIENT_IDENTIFIER), 'I`~')  PATIENT_IDENTIFIER_PHI                                      
,PERSON_CODE                                             
,RESERVED_3                                              
,ACCUMULATOR_BALANCE_COUNT                               
,ACCUMULATOR_SPECIFIC_CATEGORY_TYPE                      
,RESERVED_4                                              
,ACCUMULATOR_1_BALANCE_QUALIFIER                         
,ACCUMULATOR_1_NETWORK_INDICATOR                         
,ACCUMULATOR_1_APPLIED_AMOUNT                            
,ACCUMULATOR_1_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_1_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_1_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_1_REMAINING_BALANCE                         
,ACCUMULATOR_1_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_2_BALANCE_QUALIFIER                         
,ACCUMULATOR_2_NETWORK_INDICATOR                         
,ACCUMULATOR_2_APPLIED_AMOUNT                            
,ACCUMULATOR_2_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_2_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_2_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_2_REMAINING_BALANCE                         
,ACCUMULATOR_2_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_3_BALANCE_QUALIFIER                         
,ACCUMULATOR_3_NETWORK_INDICATOR                         
,ACCUMULATOR_3_APPLIED_AMOUNT                            
,ACCUMULATOR_3_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_3_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_3_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_3_REMAINING_BALANCE                         
,ACCUMULATOR_3_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_4_BALANCE_QUALIFIER                         
,ACCUMULATOR_4_NETWORK_INDICATOR                         
,ACCUMULATOR_4_APPLIED_AMOUNT                            
,ACCUMULATOR_4_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_4_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_4_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_4_REMAINING_BALANCE                         
,ACCUMULATOR_4_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_5_BALANCE_QUALIFIER                         
,ACCUMULATOR_5_NETWORK_INDICATOR                         
,ACCUMULATOR_5_APPLIED_AMOUNT                            
,ACCUMULATOR_5_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_5_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_5_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_5_REMAINING_BALANCE                         
,ACCUMULATOR_5_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_6_BALANCE_QUALIFIER                         
,ACCUMULATOR_6_NETWORK_INDICATOR                         
,ACCUMULATOR_6_APPLIED_AMOUNT                            
,ACCUMULATOR_6_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_6_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_6_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_6_REMAINING_BALANCE                         
,ACCUMULATOR_6_REMAINING_BALANCE_ACTION_CODE             
,RESERVED_5                                              
,ACCUMULATOR_7_BALANCE_QUALIFIER                         
,ACCUMULATOR_7_NETWORK_INDICATOR                         
,ACCUMULATOR_7_APPLIED_AMOUNT                            
,ACCUMULATOR_7_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_7_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_7_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_7_REMAINING_BALANCE                         
,ACCUMULATOR_7_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_8_BALANCE_QUALIFIER                         
,ACCUMULATOR_8_NETWORK_INDICATOR                         
,ACCUMULATOR_8_APPLIED_AMOUNT                            
,ACCUMULATOR_8_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_8_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_8_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_8_REMAINING_BALANCE                         
,ACCUMULATOR_8_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_9_BALANCE_QUALIFIER                         
,ACCUMULATOR_9_NETWORK_INDICATOR                         
,ACCUMULATOR_9_APPLIED_AMOUNT                            
,ACCUMULATOR_9_APPLIED_AMOUNT_ACTION_CODE                
,ACCUMULATOR_9_BENEFIT_PERIOD_AMOUNT                     
,ACCUMULATOR_9_BENEFIT_PERIOD_AMOUNT_ACTION_CODE         
,ACCUMULATOR_9_REMAINING_BALANCE                         
,ACCUMULATOR_9_REMAINING_BALANCE_ACTION_CODE             
,ACCUMULATOR_10_BALANCE_QUALIFIER                        
,ACCUMULATOR_10_NETWORK_INDICATOR                        
,ACCUMULATOR_10_APPLIED_AMOUNT                           
,ACCUMULATOR_10_APPLIED_AMOUNT_ACTION_CODE               
,ACCUMULATOR_10_BENEFIT_PERIOD_AMOUNT                    
,ACCUMULATOR_10_BENEFIT_PERIOD_AMOUNT_ACTION_CODE        
,ACCUMULATOR_10_REMAINING_BALANCE                        
,ACCUMULATOR_10_REMAINING_BALANCE_ACTION_CODE            
,ACCUMULATOR_11_BALANCE_QUALIFIER                        
,ACCUMULATOR_11_NETWORK_INDICATOR                        
,ACCUMULATOR_11_APPLIED_AMOUNT                           
,ACCUMULATOR_11_APPLIED_AMOUNT_ACTION_CODE               
,ACCUMULATOR_11_BENEFIT_PERIOD_AMOUNT                    
,ACCUMULATOR_11_BENEFIT_PERIOD_AMOUNT_ACTION_CODE        
,ACCUMULATOR_11_REMAINING_BALANCE                        
,ACCUMULATOR_11_REMAINING_BALANCE_ACTION_CODE            
,ACCUMULATOR_12_BALANCE_QUALIFIER                        
,ACCUMULATOR_12_NETWORK_INDICATOR                        
,ACCUMULATOR_12_APPLIED_AMOUNT                           
,ACCUMULATOR_12_APPLIED_AMOUNT_ACTION_CODE               
,ACCUMULATOR_12_BENEFIT_PERIOD_AMOUNT                    
,ACCUMULATOR_12_BENEFIT_PERIOD_AMOUNT_ACTION_CODE        
,ACCUMULATOR_12_REMAINING_BALANCE                        
,ACCUMULATOR_12_REMAINING_BALANCE_ACTION_CODE            
,OPTIONAL_DATA_INDICATOR                                 
,TOTAL_AMOUNT_PAID                                       
,TOTAL_AMOUNT_PAID_ACTION_CODE                           
,AMOUNT_OF_COPAY                                         
,AMOUNT_OF_COPAY_ACTION_CODE                             
,PATIENT_PAY_AMOUNT                                      
,PATIENT_PAY_AMOUNT_ACTION_CODE                          
,AMOUNT_ATTRIBUTED_TO_PRODUCT_SELECTION_BRAND            
,AMOUNT_ATTRIBUTED_TO_PRODUCT_SELECTION_BRAND_ACTION_CODE
,AMOUNT_ATTRIBUTED_TO_SALES_TAX                          
,AMOUNT_ATTRIBUTED_TO_SALES_TAX_ACTION_CODE              
,AMOUNT_ATTRIBUTED_TO_PROCESSOR_FEE                      
,AMOUNT_ATTRIBUTED_TO_PROCESSOR_FEE_ACTION_CODE          
,GROSS_AMOUNT_DUE                                        
,GROSS_AMOUNT_DUE_ACTION_CODE                            
,INVOICED_AMOUNT                                         
,INVOICED_AMOUNT_ACTION_CODE                             
,PENALTY_AMOUNT                                          
,PENALTY_AMOUNT_ACTION_CODE                              
,RESERVED_6                                              
,PRODUCT_SERVICE_IDENTIFIER_QUALIFIER                    
,PRODUCT_SERVICE_IDENTIFIER                              
,DAYS_SUPPLY                                             
,QUANTITY_DISPENSED                                      
,PRODUCT_SERVICE_NAME                                    
,BRAND_GENERIC_INDICATOR                                 
,THERAPEUTIC_CLASS_CODE_QUALIFIER                        
,THERAPEUTIC_CLASS_CODE                                  
,DISPENSED_AS_WRITTEN                                    
,RESERVED_7                                              
,CLIENT_KEY                                              
,JOB_KEY                                                 
,FILE_NAME                                               
,CREATED_BY                                              
,CREATED_TIMESTAMP                                       
,UPDATED_BY
,UPDATED_TIMESTAMP
FROM AHUB_DW.ACCUMULATOR_DETAIL 
)