AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  secretManager:
    Description: complete name of the secret manager service that provides credentails for connecting to redshift database
    Type: String
    Default: irx-ahub-pr-redshift-cluster
  secretDescription:
    Description: description of the secret manager
    Type: String
    Default: Access to the production redshift cluster
  KmsKeyIdSecretsManager:
    Description: KMS key to use for encryption
    Type: String
    Default: "arn:aws:kms:us-east-2:950511364051:key/105d7c82-4ea4-4b94-9ae3-b83aa2a486a3" #this is key which allows Secrets Manager and cross account access
  tagRegion:
    Description: provides the global region of AWS account used in tags
    Type: String
    Default: AWS -East 2
  tagEnvironment:
    Description: provides the environment name whose value will be replaced in few tags and also utilised by some environment variables in functions/jobs.
    Type: String
    Default: PROD
  redshiftHost:
    Description: provides the host name of the redshift cluster
    Type: String
    Default: irx-accumhub.cfimm2ocg1yh.us-east-2.redshift.amazonaws.com

Resources:

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref secretManager
      Description: !Ref secretDescription
      KmsKeyId: !Ref KmsKeyIdSecretsManager      #enable this property iff you have a valid KMS key id; it should not be defaulted to either NULL or blank
      SecretString: !Sub |                       #enter the password and hostname manually through console once the secrets manager gets deployed. These values are not to be exposed and kept hidden in CFT.
            {"username": "awsuser",
              "password": "",
              "engine": "redshift",
              "host": "",
              "port": "5439",
              "dbClusterIdentifier": "irx-accumhub",
              "role": "irx-accum-phi-redshift-glue",
              "dbname": "devdb"}
      Tags:
        -
          Key: Date/Time
          Value: 20200318101010
        -
          Key: Opt In/Opt Out
          Value: Yes
        -
          Key: BarometerIT
          Value: 041800001L7T
        -
          Key: COSTCENTER
          Value: 6590196400
        -
          Key: COMPLIANCE
          Value: PHI
        -
          Key: IT Department
          Value: Anbu Ramaiyan
        -
          Key: Database
          Value: N/A
        -
          Key: Resource Type
          Value: LAMBDA
        -
          Key: NAME
          Value: !Sub 'IRX-AHUB-SECRETSMANAGER-${tagEnvironment}'
        -
          Key: Layer
          Value: SM
        -
          Key: Owner Department
          Value: Saneeja Abdeen
        -
          Key: Virtualization Platform
          Value: N/A
        -
          Key: Operating System
          Value: N/A
        -
          Key: Company
          Value: IRX
        -
          Key: Environment
          Value: !Ref tagEnvironment
        -
          Key: Location
          Value: !Ref tagRegion