service: SFM-ES-StayFolio

custom:
  serverless-aws-resource-names:
    source: serverless-mapping.json
  deploymentBucket:
    versioning: true
  DEV:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-dev
    DOMAIN_ENDPOINT: vpc-whgloyaltyerrormonitoring-gw5w4vzpa3xbj2x7z7ua2ixgua.us-west-2.es.amazonaws.com
    cfnRole: 'arn:aws:iam::520495760791:role/CloudformationRole'
    SPMLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-SabrePMSV3Unzip-${opt:stage}
    FlattenLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-StayFolioFlatteningtoJSON-${opt:stage}
    OPMSLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-OPMSAirportIntegration-${opt:stage}
    IDSLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-IDSAirportIntegration-${opt:stage}
    SPHLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-SabrePMSV4DecryptionAirportIntegration-${opt:stage}
    glueBtchRunLogGroup: /aws/glue/stay-batch-run-${opt:stage}
    glueFolioBtchRunLogGroup: /aws/glue/folio-batch-run-${opt:stage}
    glueDQBtchRunLogGroup: /aws/glue/stay-dq-batch-run-${opt:stage}
    awsAcctId: 520495760791
    vpcDetails:
      subnetIds:
        - subnet-25bbdd40
        - subnet-6816921f
      securityGroupIds:
        - sg-d9c1b4a6
    tags:
      WHG-B-APPNM: Stay Folio Processes ES Log Streamer
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  QA:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-qa
    DOMAIN_ENDPOINT: vpc-errormonitoring-av7g623fxjs26iudjpkxrvnmya.us-west-2.es.amazonaws.com
    cfnRole: ''
    SPMLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-SabrePMSV3Unzip-${opt:stage}
    FlattenLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-StayFolioFlatteningtoJSON-${opt:stage}
    OPMSLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-OPMSAirportIntegration-${opt:stage}
    IDSLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-IDSAirportIntegration-${opt:stage}
    SPHLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-SabrePMSV4DecryptionAirportIntegration-${opt:stage}
    glueBtchRunLogGroup: /aws/glue/stay-batch-run-${opt:stage}
    glueFolioBtchRunLogGroup: /aws/glue/folio-batch-run-${opt:stage}
    glueDQBtchRunLogGroup: /aws/glue/stay-dq-batch-run-${opt:stage}
    awsAcctId: 520495760791
    vpcDetails:
      subnetIds:
        - subnet-5e6f0007
        - subnet-6816921f
      securityGroupIds:
        - sg-d9c1b4a6
    tags:
      WHG-B-APPNM: Stay Folio Processes ES Log Streamer
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  PROD:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-prod
    DOMAIN_ENDPOINT: vpc-whg-errormonitoring-t2ulqt7fbmy4myttv4kh27sqgm.us-west-2.es.amazonaws.com
    cfnRole: ''
    SPMLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-SabrePMSV3Unzip-${opt:stage}
    FlattenLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-StayFolioFlatteningtoJSON-${opt:stage}
    OPMSLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-OPMSAirportIntegration-${opt:stage}
    IDSLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-IDSAirportIntegration-${opt:stage}
    SPHLogGroup: /aws/lambda/WHG-Lambda-USW2-SFM-SabrePMSV4DecryptionAirportIntegration-${opt:stage}
    glueBtchRunLogGroup: /aws/glue/stay-batch-run-${opt:stage}
    glueFolioBtchRunLogGroup: /aws/glue/folio-batch-run-${opt:stage}
    glueDQBtchRunLogGroup: /aws/glue/stay-dq-batch-run-${opt:stage}
    awsAcctId: 574950190833
    vpcDetails:
      subnetIds:
        - subnet-3948005c
        - subnet-cf1f71b8
      securityGroupIds:
        - sg-02c3ccaf9a549af23
    tags:
      WHG-B-APPNM: Stay Folio Processes ES Log Streamer
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-west-2
  cfnRole: ${self:custom.${opt:stage}.cfnRole}
  stackTags: ${self:custom.${opt:stage}.tags}
  vpc: ${self:custom.${opt:stage}.vpcDetails}
  deploymentBucket: 
    name: ${self:custom.${opt:stage}.deploymentBucket.name}
    serverSideEncryption: AES256
  deploymentPrefix: stay/scripts/lambda/es-log-streamer
  environment:
    DOMAIN_ENDPOINT: ${self:custom.${opt:stage}.DOMAIN_ENDPOINT}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "es:*"
      Resource: 
        - "arn:aws:es:${self:provider.region}:${self:custom.${opt:stage}.awsAcctId}:domain/*"
   

functions:
  ProcessesLogStreamer:
    handler: stayLogStreamer.handler
    description: Lambda function to Stream Stay application logs from CW to ES for monitoring framework
    memorySize: 1024
    timeout: 120
    package:
      individually: true
      exclude:
        - serverless*
        - package*
    events:
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.SPMLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.FlattenLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.OPMSLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.IDSLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.SPHLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.glueBtchRunLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.glueFolioBtchRunLogGroup}'
          filter: 'source_system'
      - cloudwatchLog:
          logGroup: '${self:custom.${opt:stage}.glueDQBtchRunLogGroup}'
          filter: 'source_system'
      
plugins:
  - serverless-aws-resource-names
  - serverless-deployment-bucket





