service: Rate-Parity


custom:
  serverless-aws-resource-names:
    source: serverless-mapping.json
  deploymentBucket:
    versioning: true
  dev:
    deploymentBucket:
      name:  whg-s3-usw2a-codebase-dev
    cfnRole: ''
    redBucket: "whg-s3-usw2a-redterminal-dev"
    errorBucket: "whg-s3-usw2a-errorterminal-dev"
    goldBucket: "whg-s3-usw2a-goldterminal-dev"
    blueBucket: "whg-s3-usw2a-blueterminal-dev"
    env: "dev"
    filesToExtract: "major-issues, hotels"
    glueWorkflowsToRun: "WHG-Glue-WorkFlow-USW2-Rate-Parity-MajorIssue-${opt:stage}, WHG-Glue-WorkFlow-USW2-Rate-Parity-Hotels-${opt:stage}"
    SNSTopicArn: "arn:aws:sns:us-west-2:520495760791:WHG-SNS-Rate-Parity-UnzipFiles-${opt:stage}"
    SNSEmailNotification1: "Sagar.Jain@wyndham.com"
    SNSEmailNotification2: "aarushi.mathur@nttdata.com"
    SNSEmailNotification3: "Jabin.Valiyathodikayil@wyndham.com"
    SNSEmailNotification4: "Jabin.Valiyathodikayil@wyndham.com"
    awsAcctId: 520495760791
    tags:
      WHG-B-APPNM: OTAI
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0088715
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: DEV
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  qa:
    deploymentBucket:
      name:  whg-s3-usw2a-codebase-qa
    cfnRole: ''
    redBucket: "whg-s3-usw2a-redterminal-qa"
    errorBucket: "whg-s3-usw2a-errorterminal-qa"
    blueBucket: "whg-s3-usw2a-blueterminal-qa"
    goldBucket: "whg-s3-usw2a-goldterminal-qa"
    env: "qa"
    filesToExtract: "major-issues, hotels"
    glueWorkflowsToRun: "WHG-Glue-WorkFlow-USW2-Rate-Parity-MajorIssue-${opt:stage}, WHG-Glue-WorkFlow-USW2-Rate-Parity-Hotels-${opt:stage}"
    SNSTopicArn: "arn:aws:sns:us-west-2:520495760791:WHG-SNS-Rate-Parity-UnzipFiles-${opt:stage}"
    SNSEmailNotification1: "aysha.zady@wyndham.com"
    SNSEmailNotification2: "akshay.dudhal@wyndham.com"
    SNSEmailNotification3: "Sagar.Jain@wyndham.com"
    SNSEmailNotification4: "surjeet.das@wyndham.com"
    awsAcctId: 520495760791
    tags:
      WHG-B-APPNM: OTAI
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0088715
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: QA
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  prod:
    deploymentBucket:
      name:  whg-s3-usw2a-codebase-prod
    cfnRole: ''
    redBucket: "whg-s3-usw2a-redterminal-prod"
    errorBucket: "whg-s3-usw2a-errorterminal-prod"
    blueBucket: "whg-s3-usw2a-blueterminal-prod"
    goldBucket: "whg-s3-usw2a-goldterminal-prod"
    env: "prod"
    filesToExtract: "major-issues, hotels"
    glueWorkflowsToRun: "WHG-Glue-WorkFlow-USW2-Rate-Parity-MajorIssue-${opt:stage}, WHG-Glue-WorkFlow-USW2-Rate-Parity-Hotels-${opt:stage}"
    SNSTopicArn: "arn:aws:sns:us-west-2:574950190833:WHG-SNS-Rate-Parity-UnzipFiles-${opt:stage}"
    SNSEmailNotification1: "whrdataservices@wyndham.com"
    SNSEmailNotification2: "whrdataservices@wyndham.com"
    SNSEmailNotification3: "servicedesk.operations@wyndham.com"
    SNSEmailNotification4: "whr.incidentmanagement@wyndham.com"
    awsAcctId: 574950190833
    tags:
      WHG-B-APPNM: OTAI
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0088715
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: PROD
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  preview:
    deploymentBucket:
      name:  whg-s3-usw2a-codebase-preview
    cfnRole: ''
    redBucket: "whg-s3-usw2a-redterminal-preview"
    errorBucket: "whg-s3-usw2a-errorterminal-preview"
    blueBucket: "whg-s3-usw2a-blueterminal-preview"
    goldBucket: "whg-s3-usw2a-goldterminal-preview"
    env: "preview"
    filesToExtract: "major-issues, hotels"
    glueWorkflowsToRun: "WHG-Glue-WorkFlow-USW2-Rate-Parity-MajorIssue-${opt:stage}, WHG-Glue-WorkFlow-USW2-Rate-Parity-Hotels-${opt:stage}"
    SNSTopicArn: "arn:aws:sns:us-west-2:574950190833:WHG-SNS-Rate-Parity-UnzipFiles-${opt:stage}"
    SNSEmailNotification1: "dipankar.satpathy@wyndham.com"
    SNSEmailNotification2: "akshay.dudhal@wyndham.com"
    SNSEmailNotification3: "Sagar.Jain@wyndham.com"
    SNSEmailNotification4: "surjeet.das@wyndham.com"
    awsAcctId: 574950190833
    tags:
      WHG-B-APPNM: OTAI
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0088715
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: PRVW
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage}
  region: us-west-2
  cfnRole: ${self:custom.${opt:stage}.cfnRole}
  stackTags: ${self:custom.${opt:stage}.tags}
  deploymentBucket:
    name: ${self:custom.${opt:stage}.deploymentBucket.name}
    serverSideEncryption: AES256
  deploymentPrefix: /disparity-fee-drr/rateparity/lambda/scripts
  environment:
    redBucket: ${self:custom.${opt:stage}.redBucket}
    blueBucket: ${self:custom.${opt:stage}.blueBucket}
    errorBucket: ${self:custom.${opt:stage}.errorBucket}
    goldBucket: ${self:custom.${opt:stage}.goldBucket}
    SNSTopicArn: ${self:custom.${opt:stage}.SNSTopicArn}
    env: ${self:custom.${opt:stage}.env}
    filesToExtract: ${self:custom.${opt:stage}.filesToExtract}
    glueWorkflowsToRun: ${self:custom.${opt:stage}.glueWorkflowsToRun}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${self:custom.${opt:stage}.redBucket}/*"
        - "arn:aws:s3:::${self:custom.${opt:stage}.errorBucket}/*"
        - "arn:aws:s3:::${self:custom.${opt:stage}.blueBucket}/*"
        - "arn:aws:s3:::${self:custom.${opt:stage}.goldBucket}/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${self:custom.${opt:stage}.blueBucket}"
        - "arn:aws:s3:::${self:custom.${opt:stage}.redBucket}"
        - "arn:aws:s3:::${self:custom.${opt:stage}.errorBucket}"
        - "arn:aws:s3:::${self:custom.${opt:stage}.goldBucket}"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "${self:custom.${opt:stage}.SNSTopicArn}"
    - Effect: Allow
      Action:
        - "glue:StartJobRun"
        - "glue:GetJobRuns"
        - "glue:StartWorkflowRun"
        - "glue:GetWorkflowRuns"
        - "glue:ListWorkflows"
        - "glue:GetWorkflow"
      Resource:
        - "*"
functions:
  UnzipFiles:
    handler: rateparitydtl.main
    memorySize: 3008
    timeout: 900
    description: Lambda to process rate parity detail feed
    layers:
      - {Ref: RequestslayerLambdaLayer} 
    package:
      individually: true
      exclude:
        - python-requests*      
    events:
      - schedule:
            Description: Rate Parity Event Trigger
            Name: RTPRTTrigger-${opt:stage}
            rate: "cron(00 16 ? * FRI *)"
            enabled: true
      - s3:
          bucket: ${self:custom.${opt:stage}.redBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: otai/disparity/summary/
            - suffix: .zip
          existing: true
      
layers:
  Requestslayer:
    name: Python-Requests-Lib-UnzipFiles
    description: Python Libarary to support Encode Decode of file
    package:
      artifact: "./python.zip"
    compatibleRuntimes: 
      - python3.9

resources:
  Resources:
    ErrorTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: WHG-SNS-Rate-Parity-UnzipFiles-${opt:stage}
    ErrorTopicSubscribeOne:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: !Ref ErrorTopic
        Protocol: email
        Endpoint: ${self:custom.${opt:stage}.SNSEmailNotification1}
    ErrorTopicSubscribeTwo:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: !Ref ErrorTopic
        Protocol: email
        Endpoint: ${self:custom.${opt:stage}.SNSEmailNotification2}
    ErrorTopicSubscribeThree:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: !Ref ErrorTopic
        Protocol: email
        Endpoint: ${self:custom.${opt:stage}.SNSEmailNotification3}
    ErrorTopicSubscribeFour:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn: !Ref ErrorTopic
        Protocol: email
        Endpoint: ${self:custom.${opt:stage}.SNSEmailNotification4}
   
            


package:
  exclude:
    - serverless*.*
    - package*.*
    - node_modules/**

plugins:
  - serverless-aws-resource-names
  - serverless-deployment-bucket
  - serverless-plugin-aws-alerts