service: SFM-StayFolio

custom:
  serverless-aws-resource-names:
    source: serverless-mapping.json
  deploymentBucket:
    versioning: true
  DEV:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-dev
    blueBucket: whg-s3-usw2a-blueterminal-dev
    errorBucket: whg-s3-usw2a-errorterminal-dev
    goldBucket: whg-s3-usw2a-goldterminal-dev
    SNSTopicArn: arn:aws:sns:us-west-2:520495760791:WHG-SNS-UW2-SFM-StayFolio-Alerts-${opt:stage}
    cfnRole: "arn:aws:iam::520495760791:role/CloudformationRole"
    tags:
      WHG-B-APPNM: SFM Stay-Folio Flattening
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  QA:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-qa
    blueBucket: whg-s3-usw2a-blueterminal-qa
    errorBucket: whg-s3-usw2a-errorterminal-qa
    goldBucket: whg-s3-usw2a-goldterminal-qa
    SNSTopicArn: arn:aws:sns:us-west-2:520495760791:WHG-SNS-UW2-SFM-StayFolio-Alerts-${opt:stage}
    cfnRole: ''
    tags:
      WHG-B-APPNM: SFM Stay-Folio Flattening
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
  PROD:
    deploymentBucket: 
      name:  whg-s3-usw2a-codebase-prod
    blueBucket: whg-s3-usw2a-blueterminal-prod
    errorBucket: whg-s3-usw2a-errorterminal-prod
    goldBucket: whg-s3-usw2a-goldterminal-prod
    SNSTopicArn: arn:aws:sns:us-west-2:574950190833:WHG-SNS-UW2-SFM-StayFolio-Alerts-${opt:stage}
    cfnRole: ''
    tags:
      WHG-B-APPNM: SFM Stay-Folio Flattening
      WHG-B-BO: Derek Barbara
      WHG-B-DEP: Data Services
      WHG-B-PRJ: PRJ0091640
      WHG-O-AUT: N/A
      WHG-O-DDT: N/A
      WHG-REG: USW2
      WHG-T-COMP: N/A
      WHG-T-ENV: ${opt:stage}
      WHG-T-POC: Derek Barbara
      WHG-T-SER: Data Services
      WHG-T-TIER: APP
    
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage}
  stackTags: ${self:custom.${opt:stage}.tags}
  cfnRole: ${self:custom.${opt:stage}.cfnRole}
  deploymentBucket: 
    name: ${self:custom.${opt:stage}.deploymentBucket.name}
    serverSideEncryption: AES256
  deploymentPrefix: stay/scripts/lambda/flattening
  environment:
    blueBucket: ${self:custom.${opt:stage}.blueBucket}
    errorBucket: ${self:custom.${opt:stage}.errorBucket}
    goldBucket: ${self:custom.${opt:stage}.goldBucket}
    SNSTopicArn: ${self:custom.${opt:stage}.SNSTopicArn}
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: 
        - "arn:aws:s3:::${self:custom.${opt:stage}.blueBucket}"
        - "arn:aws:s3:::${self:custom.${opt:stage}.errorBucket}"
        - "arn:aws:s3:::${self:custom.${opt:stage}.goldBucket}"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: 
        - "arn:aws:s3:::${self:custom.${opt:stage}.blueBucket}/*"
        - "arn:aws:s3:::${self:custom.${opt:stage}.errorBucket}/*"
        - "arn:aws:s3:::${self:custom.${opt:stage}.goldBucket}/*"
    - Effect: "Allow"
      Action:
        - "sns:Publish" 
      Resource:
        - "${self:custom.${opt:stage}.SNSTopicArn}"
    
functions:
  FlatteningtoJSON:
    handler: handler.index
    memorySize: 2048
    timeout: 600
    description: Lambda Function to Flatten Sabre Reference Rate Plan XML Data to Normalized JSON and storing it to S3 Bucket
    events:
      - s3:
          bucket: ${self:custom.${opt:stage}.blueBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: pms_stay/payload/
            - suffix: .xml
          existing: true
      - s3:
          bucket: ${self:custom.${opt:stage}.blueBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: pms_folio/payload/
            - suffix: .xml
          existing: true

package:
  exclude:
    - serverless*.*
    - package*.*

plugins:
  - serverless-aws-resource-names
  - serverless-deployment-bucket